name: Output Event Details
on:  [issues, workflow_dispatch]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output details
        run: |
          echo "${{ toJSON(github) }}"
          echo "${{ toJSON(github.event) }}"