name: Output Event Details
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    - name: Get code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Output details
      run: echo "${{ toJSON(github) }}"